### PR TITLE
adding linux makefile

### PR DESCRIPTION
**Pull request by Ezbob**
Makefile for linux plus x86_64 library files and headers

### CODE REVIEW

**Comment by Tiggles** [comment]
Isn't the existing makefile already for Linux?

**Comment by Ezbob** [comment]
A lot of the link libraries (-l library flags) in the makefile are windows only, such as `-lmsvcrt` .
And the `-Wl,-subsystem=gui` flag is only for Windows Subsystem Linux. If you run it on a standalone Linux machine or a VM like VirtualBox, then the linker will complain.

**Comment by Tiggles** [comment]
Then I think changing the current file rather than adding a new one is better.

**Comment by Tiggles** [comment]
And I am assuming this build the entire library as well?

**Comment by Ezbob** [comment]
... Been away on vacation ...

> Then I think changing the current file rather than adding a new one is better.

Well it depends on the platforms you want to support... You could also consider using CMake, as CMake can generate Makefiles, Microsoft VS solution files etc. for your project..

> And I am assuming this build the entire library as well?

Nope, I've included the Linux shared objects and headers that was compiled for an x86_64 machine, so you can link with the raylib easily

**Comment by Ezbob** [comment]
CMake support is probably better for cross-platform compilations

**Pull request closed without merging**
